### 1. Generate a tuple from the set ["aman", "222", 777, 400.4] 

In [ ]:
a=tuple(["aman","222",777,400.4])
print(a)

('aman', '222', 777, 400.4)


### 2. Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys.

In [ ]:
d2={"rollno": "CB.EN.U4CSE20221","last_name": "sai","first_name": "venkat","dob": "09-09-2002"}
print(d2)

{'rollno': 'CB.EN.U4CSE20203', 'last_name': 'A', 'first_name': 'Tarun', 'dob': '12-12-2001'}


### 3. Use rand function to generate a 2-dimensional random array with seed.

In [1]:
import random
import numpy as np
from numpy import random
np.random.seed(5)
x=random.randint(10,size=(2,2))
print(x)


[[3 6]
 [6 0]]


### 4. Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)

In [ ]:
import random
print(round(random.uniform(0.1, 1.0), 10))
print(abs(-1234))

0.9414873335
1234


### 5. Return a random integer N such that 20 <= N <= 90.

In [ ]:
import random 
print(random.randint(20,91))

52


### 6. Given a population or set[11, 12, 13,14, 15]

o Return a 3 length list of unique elements without replacement.

o Shuffle the above set

o Print a random number from the set

In [ ]:
a=[11,12,13,14,15]
print(a[:3])
print(a[random.randint(0,5)])

[11, 12, 13]
15


### 7. Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.

In [ ]:
file=open("file1.txt","w")
file.write("The King is Dead, Long Live The King")
file.close()
file=open("file1.txt","r")
for i in file:
  print(i,end=" ")

The King is Dead, Long Live The King 

### 8. Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue.

In [ ]:
def compare(x,y):
  if x>y:
    print("x greater than y")
  elif x<y:
    print("y greater than x")
  else:
    print("x equal to y")
compare(10,1)

x greater than y


### 9. Given a string "The King is Dead, Long Live The King"

o Print the complete string

o Print first character of the string

o Print characters starting from 3rd to 5th

o Print string starting from 3rd character

o Split the words

In [ ]:
a="The King is Dead, Long Live The King"
print(a)
print(a[0])
print(a[2:5])
print(a[2:])
print(a.split())

The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


### 9. An array can be created from a list: Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements

In [ ]:
a=[1,4,5,8]
print(a[:2])

[1, 4]


### 10. Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


### 11. Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).

o Slice and display the 2nd row.

o Write code to display as array([2., 5.])

o Find the length of the array.



In [ ]:
print(a[1])
print(a[0][1],a[1][1])
print(len(a))

[4 5 6]
2 5
2


12. Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
arr=arr.reshape(2,5)
print(arr)

[1 2 3 4 5 6 7 8 9 0]
[[1 2 3 4 5]
 [6 7 8 9 0]]


### 13. Create an array from a list of 1,2 and 3.

### 14. Fill an array [1,2,3] with a single value [9,9,9].

In [ ]:
a=[1,2,3]
a=np.full((3),9)
print(a)

[9 9 9]


### 15. Sum the elements of array [2,4,5].

In [ ]:
a=[2,4,5]
print(sum(a))

11


### 16. Give the products of array [77,74,75]

In [ ]:
a=[77,74,75]
product=1
for i in a:
  product*=i
print(product)

427350


### 17. Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.

In [ ]:
from scipy import stats
a=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean=",np.mean(a))
print("Median=",np.median(a))
print("Mode=",stats.mode(a))
print("Max=",max(a))
print("Min=",min(a))


Mean= 12.461538461538462
Median= 2.0
Mode= ModeResult(mode=array([1]), count=array([4]))
Max= 56
Min= 1


### 18. Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it. 

In [ ]:
a=[1, 1, 4, 5, 5, 5, 7]
a=list(set(a))
a.sort()
print(a)

[1, 4, 5, 7]


### 19. Find dot product of two arrays [1, 2, 3]and [0, 1, 1].

In [ ]:
a=[1,2,3]
b=[0,1,1]
print(np.dot(a,b))

5


### 20. Find the eigenvalues and eigenvectors of matrix A.

In [ ]:
a=[[2,-12],[1,-5]]
x,y=np.linalg.eig(a)
print(x,y)

[-1. -2.] [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


### 21. Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.

In [ ]:
a=[[11, 22, 11, 31], [25, 33, 31, 28]]
print(np.corrcoef(a))

[[1.         0.15997968]
 [0.15997968 1.        ]]
